 const TYPES_CART = {
  // Action Types
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  SUBTRACT_QUANTITY: 'SUBTRACT_QUANTITY',
  ADD_QUANTITY: 'ADD_QUANTITY',
}

export default TYPES_CART